### ISSUE TITLE
Bot staying on Vocal after inactivity

### ISSUE THREAD

**Issue by Yoyoshix** [YumeChan-DT/DreamJockey#3]
Title says it all.
Just add some kind of timeout when no music is playing for ~5min

**Comment by SakuraIsayeki** [comment]
Acknowledged the issue, thanks!

**Comment by SakuraIsayeki** [comment]
Implementation as of 1.1 is the following : 
DreamJockey plugin will disconnect any leftover channel sessions, provided that the Bot is the only user left in the channel.
